db:
  image: postgres
  ports:
    - "5432"

web:
  build: .
  command: >
    /bin/bash -c '
    sleep 3 &&
    python3 manage.py migrate &&
    ./with_host.sh python3 manage.py runserver 0.0.0.0:8079'
  volumes:
    - .:/src
  environment:
    DEBUG: 'True'
    PORT: 8079
    DATABASE_URL: postgres://postgres@db:5432/postgres
    STATUS_TOKEN: 'test-token'
  env_file: .env
  ports:
    - "8079:8079"
  links:
    - db

watch:
  image: micromasters_web
  command: >
    /bin/bash -c '
    npm cache clean &&
    npm install --no-bin-links &&
    npm rebuild node-sass &&
    echo Finished npm install &&
    node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js --config webpack.config.dev.js -d --content-base ./static --host 0.0.0.0 --port 8078 --progress --inline --hot'
  ports:
    - "8078:8078"
  volumes:
    - .:/src
