version: 2
jobs:
  build:
    working_directory: ~/micromasters
    machine:
      enabled: true
    steps:
      - checkout
      - run: sudo pip install docker-compose
      - run: cp .env.example .env
      - run: docker-compose -f travis-docker-compose.yml build
      - run: docker-compose -f travis-docker-compose.yml up -d
      - run:
          name: Python
          command: docker-compose exec web tox
      - run:
          name: Javascript
          command: sh js_test.sh
      - run:
          name: Selenium
          command: |
            docker-compose -f travis-docker-compose.yml up -d
            docker run --name travis-watch-container --env-file .env -e NODE_ENV=production -t travis-watch ./webpack_if_prod.sh
            docker cp travis-watch-container:/src/webpack-stats.json .
            docker cp travis-watch-container:/src/static/bundles ./static/bundles
            docker-compose -f travis-docker-compose.yml run -e DEBUG=False -e DJANGO_LIVE_TEST_SERVER_ADDRESS=0.0.0.0:8286 selenium py.test ./selenium_tests
